trabajowebparcial/ProyectoWeb/Controllers/ProductoController.cs
using Business;
using Business.Implementacion;
using Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoWeb.Controllers
{
    public class ProductoController : Controller
    {

        private IProductoService productoservice = new ProductoService();
        private ITipoProductoService tproductoservice = new TipoProductoService();

        // GET: Producto
        public ActionResult Index()
        {
            return View(productoservice.readAll());
        }

        // GET: Producto/Details/5
        public ActionResult Details(int id)
        {
            Producto pro = new Producto()
            {
                IdProducto = id
            };
            return View(productoservice.findForId(pro));
        }

        // GET: Producto/Create
        public ActionResult Create()
        {
            Producto pro = new Producto()
            {
                TipoProductoList = new SelectList(tproductoservice.readAll(), "IdTipoProducto", "Descripcion")
            };

            return View(pro);
        }

        // POST: Producto/Create
        [HttpPost]
        public ActionResult Create(Producto pro)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    productoservice.create(pro);
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Producto/Edit/5
        public ActionResult Edit(int id)
        {
            Producto pro = new Producto()
            {
                
                IdProducto = id
            };
          
            return View(productoservice.findForId(pro));
        }

        // POST: Producto/Edit/5
        [HttpPost]
        public ActionResult Edit(Producto pro)
        {

            // TODO: Add update logic here
            if (ModelState.IsValid)
            {
                productoservice.update(pro);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        // GET: Producto/Delete/5
        public ActionResult Delete(int id)
        {
            Producto pro = new Producto();
            pro.IdProducto = id;
            return View(productoservice.findForId(pro));
        }

        // POST: Producto/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Producto pro = new Producto();
                pro.IdProducto = id;
                if (ModelState.IsValid)
                {
                    productoservice.eliminar(pro);
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

trabajowebparcial/ProyectoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Bembos App</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bembos", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Productos", "Index", "Producto")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bembos</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>